#! /bin/bash
set -e

files="
/usr/share/texmf/web2c/texmf.cnf
"

for f in $files
do
    backup=/var/lib/texlive-data-ja-overrides/saved$f

    csum1=$(sha1sum $f | cut -f 1 -d ' ')
    csum2=$(sha1sum $backup | cut -f 1 -d ' ')

    if test "x$csum1" = "x$csum2"; then
        echo "[Info] Looks already backed up. Skip it: $f"
    else
        echo "[Info] Restore from backup: $f"
        cp -af $backup $f
    fi
done
