all:
	pytest test_fizzbuzz.py::test_fizzbuzz

red_1:
	pytest test_fizzbuzz.py::test_fizzbuzz_red_1

green_1:
	pytest test_fizzbuzz.py::test_fizzbuzz_green_1

red_2:
	pytest test_fizzbuzz.py::test_fizzbuzz_red_2

green_2:
	pytest test_fizzbuzz.py::test_fizzbuzz_green_2

red_3:
	pytest test_fizzbuzz.py::test_fizzbuzz_red_3

green_3:
	pytest test_fizzbuzz.py::test_fizzbuzz_green_3

red_4:
	pytest test_fizzbuzz.py::test_fizzbuzz_red_4

green_4:
	pytest test_fizzbuzz.py::test_fizzbuzz_green_4

red_5:
	pytest test_fizzbuzz.py::test_fizzbuzz_red_5

green_5:
	pytest test_fizzbuzz.py::test_fizzbuzz_green_5
